# Generated by Django 2.0.5 on 2018-08-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('stok', models.IntegerField(default=0)),
                ('waktu', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
