# Generated by Django 2.0.5 on 2018-08-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'verbose_name_plural': 'Barang'},
        ),
    ]
